# 鸢尾花--sklearn比较

In [1]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
from sklearn import datasets
iris=datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
Xtrain, Xtest, ytrain, ytest = train_test_split(iris.data,
                                               iris.target,
                                               random_state=12)

In [4]:
#GaussianNB().fit(Xtrain, ytrain).score(Xtest,ytest)
clf_G = GaussianNB().fit(Xtrain, ytrain)
clf_G.score(Xtest,ytest)

0.9736842105263158

In [5]:
clf_G.predict(Xtest)

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1,
       2, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1])

In [6]:
clf_G.predict_proba(Xtest)

array([[1.00000000e+000, 2.48682219e-017, 1.93944397e-023],
       [9.28367402e-152, 2.48576754e-002, 9.75142325e-001],
       [1.00000000e+000, 7.19905878e-018, 3.66747133e-024],
       [3.17052477e-075, 9.99751806e-001, 2.48194200e-004],
       [6.74294741e-236, 4.45798016e-009, 9.99999996e-001],
       [1.14666509e-171, 1.95814902e-003, 9.98041851e-001],
       [8.02657454e-203, 2.34481513e-007, 9.99999766e-001],
       [1.00000000e+000, 2.65988076e-017, 2.71713921e-023],
       [9.35786493e-256, 9.07196638e-011, 1.00000000e+000],
       [1.00000000e+000, 1.04869246e-010, 2.74935070e-017],
       [3.31263227e-100, 9.87428016e-001, 1.25719837e-002],
       [1.00000000e+000, 6.08575475e-016, 9.48633644e-022],
       [1.00000000e+000, 9.86541185e-014, 4.85401488e-020],
       [1.00000000e+000, 4.14364090e-015, 3.31354267e-021],
       [3.03132054e-109, 7.85918892e-001, 2.14081108e-001],
       [6.45984775e-206, 8.36611919e-006, 9.99991634e-001],
       [2.25647136e-191, 5.52863568e-004

In [7]:
accuracy_score(ytest, clf_G.predict(Xtest))

0.9736842105263158

In [8]:
MultinomialNB().fit(Xtrain, ytrain).score(Xtest,ytest)

0.9736842105263158

In [9]:
BernoulliNB().fit(Xtrain, ytrain).score(Xtest,ytest)

0.2894736842105263

# 鸢尾花--手写代码

## 导入数据集

In [10]:
import pandas as pd
import numpy as np

In [11]:
dataSet = pd.read_csv('iris.csv')
print(type(dataSet))
#pd.concat

<class 'pandas.core.frame.DataFrame'>


## 切分数据集和测试集

In [12]:
import random
"""
函数功能：随机切分训练集和测试集
参数说明：
   dataSet:输入的数据集
   rate：训练集所占比例
返回：切分好的训练集和测试集
"""
def randSplit(dataSet, rate):
    l = list(dataSet.index)                 #提取出索引
    random.shuffle(l)                       #随机打乱索引
    dataSet.index = l                       #将打乱后的索引重新赋值给原数据集
    n = dataSet.shape[0]                    #总行数
    m = int(n * rate)                       #训练集的数量
    train = dataSet.loc[range(m), :]        #提取前m个记录作为训练集
    test = dataSet.loc[range(m, n), :]      #剩下的作为测试集
    dataSet.index = range(dataSet.shape[0]) #更新原数据集的索引
    test.index = range(test.shape[0])       #更新测试集的索引
    return train, test

In [13]:
train, test = randSplit(dataSet, 0.9)

In [14]:
train.head()

sepal_length  sepal_width  petal_length  petal_width     species
0           5.6          3.0           4.1          1.3  versicolor
1           6.2          2.9           4.3          1.3  versicolor
2           6.0          2.7           5.1          1.6  versicolor
3           6.9          3.1           4.9          1.5  versicolor
4           4.9          3.1           1.5          0.1      setosa

In [15]:
train.iloc[:,-1].value_counts()

versicolor    47
setosa        46
virginica     42
Name: species, dtype: int64

In [16]:
labels = train.iloc[:,-1].value_counts().index

In [17]:
labels

Index(['versicolor', 'setosa', 'virginica'], dtype='object')

In [18]:
train.loc[train.iloc[:,-1]=='virginica',:].mean()   

sepal_length    6.595238
sepal_width     2.976190
petal_length    5.569048
petal_width     2.028571
dtype: float64

## 构建高斯朴素贝叶斯分类器

In [19]:
labels = train.iloc[:,-1].value_counts().index   #将训练集的标签提取出来
mean = []         #均值(正态分布)
std = []          #方差 
result = []       #存放测试集的预测结果

for i in labels:
    item = train.loc[train.iloc[:,-1]==i,:]    #分别提取出每一种类别
    m = item.iloc[:,:-1].mean()                 #当前类别的平均值(去掉最后一列)
    s = np.sum((item.iloc[:,:-1]-m)**2)/(item.shape[0])   #当前类别的方差
    mean.append(m)                                        #将当前类别的平均值追加至列表
    std.append(s)                                         #将当前类别的方差追加至列表
means = pd.DataFrame(mean,index=labels)                   #变成DF格式，索引为类标签
stds = pd.DataFrame(std,index=labels)                     #变成DF格式，索引为类标签

In [20]:
means

sepal_length  sepal_width  petal_length  petal_width
versicolor      5.931915     2.744681      4.263830     1.317021
setosa          4.984783     3.395652      1.452174     0.236957
virginica       6.595238     2.976190      5.569048     2.028571

In [21]:
def classify_GN(train,test):
    labels = train.iloc[:,-1].value_counts().index   #将训练集的标签提取出来
    mean = []         #均值(正态分布)
    std = []          #方差 
    result = []       #存放测试集的预测结果

    ## 将每一类的均值和方差提取出来
    for i in labels:
        item = train.loc[train.iloc[:,-1]==i,:]    #分别提取出每一种类别
        m = item.iloc[:,:-1].mean()                 #当前类别的平均值(去掉最后一列)
        s = np.sum((item.iloc[:,:-1]-m)**2)/(item.shape[0])   #当前类别的方差
        mean.append(m)                                        #将当前类别的平均值追加至列表
        std.append(s)                                         #将当前类别的方差追加至列表
    means = pd.DataFrame(mean,index=labels)                   #变成DF格式，索引为类标签
    stds = pd.DataFrame(std,index=labels)                     #变成DF格式，索引为类标签
    for j in range(test.shape[0]):
        iset = test.iloc[j,:-1].tolist()                      #当前测试实例
        iprob = np.exp(-1*(iset-means)**2/(stds*2))/(np.sqrt(2*np.pi*stds)) #正态分布公式
        prob = 1                                              #初始化当前实例总概率
        for k in test.columns[0:4]:                  #遍历每个特征
            prob = prob * iprob[k]                                   #特征概率之积即为当前实例概率#类别？
            cla = prob.index[np.argmax(prob.values)]          #返回最大概率的类别
        result.append(cla)
    test['predict'] = result
    acc = (test.iloc[:,-1]==test.iloc[:,-2]).mean()           #计算预测准确率
    print('模型预测准确率为：',acc)
    return test

In [22]:
classify_GN(train,test)

模型预测准确率为： 0.9333333333333333


sepal_length  sepal_width  petal_length  petal_width     species  \
0            5.4          3.9           1.3          0.4      setosa   
1            6.3          3.4           5.6          2.4   virginica   
2            6.4          2.7           5.3          1.9   virginica   
3            6.0          2.2           5.0          1.5   virginica   
4            6.4          3.2           5.3          2.3   virginica   
5            5.6          2.9           3.6          1.3  versicolor   
6            6.2          2.8           4.8          1.8   virginica   
7            5.1          3.8           1.9          0.4      setosa   
8            6.4          3.2           4.5          1.5  versicolor   
9            6.5          3.0           5.5          1.8   virginica   
10           7.2          3.6           6.1          2.5   virginica   
11           5.7          4.4           1.5          0.4      setosa   
12           6.0          3.4           4.5          1.6  versicolor   
13           4.8          3.1           1.6          0.2      setosa   
14           7.4          2.8           6.1          1.9   virginica   

       predict  
0       setosa  
1    virginica  
2    virginica  
3   versicolor  
4    virginica  
5   versicolor  
6    virginica  
7       setosa  
8   versicolor  
9    virginica  
10   virginica  
11      setosa  
12  versicolor  
13      setosa  
14   virginica

In [24]:
for j in range(test.shape[0]):
    iset = test.iloc[j,:-1].tolist()                      #当前测试实例
    iprob = np.exp(-1*(iset-means)**2/(stds*2))/(np.sqrt(2*np.pi*stds)) #正态分布公式
    prob = 1                                              #初始化当前实例总概率
    for k in test.columns[0:4]:                  #遍历每个特征
        prob = prob * iprob[k]                                  #特征概率之积即为当前实例概率
        cla = prob.index[np.argmax(prob.values)]          #返回最大概率的类别
    result.append(cla)

ValueError: Unable to coerce to Series, length must be 4: given 5

In [ ]:
test.iloc[j,:-1]

In [ ]:
prob

In [ ]:
for i in range(20):
    train,test= randSplit(dataSet, 0.8)
    classify_GN(train,test)