In [3]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
#2：min()、max()函数

In [4]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()

In [5]:
print(zmin)
print(zmax)

0.0043072198627
0.991803488957


#  归一化

In [7]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print (z)
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print(z)

[[ 7.8987001   8.35922003  5.99086447  1.5016672   2.83285561]
 [ 7.46417701  1.87813591  3.83950012  9.64429448  2.33978022]
 [ 3.33798635  5.56843844  1.2252132   2.49295747  3.33487852]
 [ 7.61400208  2.67816028  5.85459007  3.11099861  7.58981982]
 [ 5.48935621  5.0774473   2.48460469  6.87024789  6.90293774]]
[[ 0.79266213  0.84736168  0.5660536   0.0328366   0.19095224]
 [ 0.74105043  0.07755273  0.31051926  1.          0.13238582]
 [ 0.25095056  0.51587876  0.          0.15057988  0.25058142]
 [ 0.75884632  0.17257787  0.54986723  0.22398945  0.75597401]
 [ 0.50648555  0.45755991  0.14958776  0.67050483  0.67438766]]


In [12]:
#矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
#print np.arange(5)
print(z)


[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [14]:
#生成0~10之间均匀分布的11个数，包括0和10

z = np.linspace(0,10,11,endpoint=True,retstep=True)
print(z)
z = np.linspace(0,10,11)
z


(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]), 1.0)


array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [18]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo