In [1]:
#做判断，bool
import numpy
vector = numpy.array([5, 10, 15, 20])
vector == 10

array([False,  True, False, False], dtype=bool)

In [2]:
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [3]:
#用bool值当成 索引 传到array中，返回True
vector = numpy.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])
#选择bool=Ture的值

[False  True False False]
[10]


In [4]:
#对矩阵进行操作
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
second_column_25 = (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25, :])

[False  True False]
[[20 25 30]]


In [5]:
#We can also perform comparisons with multiple conditions
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [6]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [10]:
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
print(vector)

In [12]:
matrix = numpy.array([
            [5, 10, 15], 
            [20, 25, 30],
            [35, 40, 45]
         ])
second_column_25 = matrix[:,1] == 25
print(second_column_25)
matrix[second_column_25, 1] = 10
print(matrix)

[False  True False]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [15]:
vector = numpy.array(["1", "2", "3"])
print(vector)
vector = vector.astype(float)#str值整体转化为float型
print(vector)
vector.dtype

['1' '2' '3']
[ 1.  2.  3.]


dtype('float64')

In [19]:
#属性
vector = numpy.array([5, 10, 15, 20])
vector.max()

20

In [20]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(1)
# 1  按照行

array([ 30,  75, 120])

In [21]:
matrix = numpy.array([
                [5, 10, 15], 
                [20, 25, 30],
                [35, 40, 45]
             ])
matrix.sum(0)
# 0  按照列

array([60, 75, 90])

In [22]:
#replace nan value with 0
#文件读取
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",")
print(world_alcohol)
is_value_empty = numpy.isnan(world_alcohol[:,4])
print(is_value_empty)
world_alcohol[is_value_empty, 4] = '0'
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float)
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()
average_alcohol

[[             nan              nan              nan              nan
               nan]
 [  1.98600000e+03              nan              nan              nan
    0.00000000e+00]
 [  1.98600000e+03              nan              nan              nan
    5.00000000e-01]
 ..., 
 [  1.98700000e+03              nan              nan              nan
    7.50000000e-01]
 [  1.98900000e+03              nan              nan              nan
    1.50000000e+00]
 [  1.98500000e+03              nan              nan              nan
    3.10000000e-01]]
[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False  True False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False F

1.140060120240481

In [23]:
total_alcohol

1137.78