In [2]:
import numpy
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",",dtype=str)
world_alcohol
#numpy.ndarray
#1.98600000e+03 is actually 1.986 * 10 ^ 3

array([['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ..., 
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']],
      dtype='<U52')

In [3]:
#list
vector = numpy.array([5, 10, 15, 20])
matrix = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])#里面传的数值是list
vector

array([ 5, 10, 15, 20])

In [4]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
#ndarray.shape
vector = numpy.array([1, 2, 3, 4])
print(vector.shape)
matrix = numpy.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(4,)
(2, 3)


(2, 3)

In [11]:
numbers = numpy.array([1,2,3,"4"])
print(numbers)
numbers.dtype

['1' '2' '3' '4']


dtype('<U11')

In [12]:
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ..., 
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']],
      dtype='<U75')

In [13]:
#怎么样取矩阵中的值，通过索引
uruguay_other_1986 = world_alcohol[1,4]
third_country = world_alcohol[2,2]
print(uruguay_other_1986)
print(third_country)

0.5
Cte d'Ivoire


In [14]:
#切片
vector = numpy.array([5, 10, 15, 20])
print(vector[0:3])  

[ 5 10 15]


In [15]:
#取列
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,1])

[10 25 40]


In [16]:
#取几列，切片
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [ ]:
#取行列
matrix = numpy.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])
print(matrix[1:3,0:2])