In [1]:
import numpy as np
B = np.arange(3)
print (B)
print (np.exp(B))
print (np.sqrt(B))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [15]:

a = np.floor(10*np.random.random((3,4)))#向下的取整
print (a)
print("____")

#a.shape
## flatten the array
print (a.ravel())#矩阵拉成了向量
print("____")
a.reshape (3,-1)
print (a)
print("____")
a.shape = (6, 2)
print(a)
print("____")
print (a.T)
print("____")
a.resize((4,3))
print (a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)

[[ 1.  1.  9.  5.]
 [ 1.  7.  7.  9.]
 [ 4.  4.  4.  4.]]
____
[ 1.  1.  9.  5.  1.  7.  7.  9.  4.  4.  4.  4.]
____
[[ 1.  1.  9.  5.]
 [ 1.  7.  7.  9.]
 [ 4.  4.  4.  4.]]
____
[[ 1.  1.]
 [ 9.  5.]
 [ 1.  7.]
 [ 7.  9.]
 [ 4.  4.]
 [ 4.  4.]]
____
[[ 1.  9.  1.  7.  4.  4.]
 [ 1.  5.  7.  9.  4.  4.]]
____
[[ 1.  1.  9.]
 [ 5.  1.  7.]
 [ 7.  9.  4.]
 [ 4.  4.  4.]]


In [17]:
#矩阵的拼接   
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print ('---')
print (b)
print ('---')
print (np.hstack((a,b)))#横着拼
print ('---')
print (np.vstack((a,b)))#竖着拼


[[ 5.  3.]
 [ 2.  8.]]
---
[[ 2.  0.]
 [ 2.  7.]]
---
[[ 5.  3.  2.  0.]
 [ 2.  8.  2.  7.]]
---
[[ 5.  3.]
 [ 2.  8.]
 [ 2.  0.]
 [ 2.  7.]]


In [22]:
#数据切分
a = np.floor(10*np.random.random((3,12)))
print (a)
print ('---')
print (np.hsplit(a,3))
print ('---')
print (np.hsplit(a,(3,4)) )  # 传（3,4）元祖，在3,4位置切分
a = np.floor(10*np.random.random((12,3)))
print ('---')
print (a)
print(np.vsplit(a,3))

[[ 1.  5.  3.  5.  3.  7.  6.  1.  3.  3.  1.  5.]
 [ 4.  5.  3.  9.  4.  3.  7.  5.  2.  5.  1.  7.]
 [ 4.  1.  2.  1.  7.  0.  8.  3.  1.  3.  2.  2.]]
---
[array([[ 1.,  5.,  3.,  5.],
       [ 4.,  5.,  3.,  9.],
       [ 4.,  1.,  2.,  1.]]), array([[ 3.,  7.,  6.,  1.],
       [ 4.,  3.,  7.,  5.],
       [ 7.,  0.,  8.,  3.]]), array([[ 3.,  3.,  1.,  5.],
       [ 2.,  5.,  1.,  7.],
       [ 1.,  3.,  2.,  2.]])]
---
[array([[ 1.,  5.,  3.],
       [ 4.,  5.,  3.],
       [ 4.,  1.,  2.]]), array([[ 5.],
       [ 9.],
       [ 1.]]), array([[ 3.,  7.,  6.,  1.,  3.,  3.,  1.,  5.],
       [ 4.,  3.,  7.,  5.,  2.,  5.,  1.,  7.],
       [ 7.,  0.,  8.,  3.,  1.,  3.,  2.,  2.]])]
---
[[ 3.  6.  9.]
 [ 3.  1.  1.]
 [ 8.  1.  7.]
 [ 2.  9.  4.]
 [ 4.  6.  7.]
 [ 5.  3.  4.]
 [ 7.  1.  6.]
 [ 6.  5.  7.]
 [ 9.  1.  3.]
 [ 6.  5.  4.]
 [ 4.  7.  2.]
 [ 1.  9.  4.]]
[array([[ 3.,  6.,  9.],
       [ 3.,  1.,  1.],
       [ 8.,  1.,  7.],
       [ 2.,  9.,  4.]]), array([[ 4.,  6., 

In [26]:
#复制操作
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print(b is a)
b.shape = 3,4
print(b)
print(a)
print (a.shape)

True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [30]:
#The view method creates a new array object that looks at the same data.
#复制 值一样，所指向的位置都不一样
c = a.view()
print(c is a)
c.shape = 2,6
print( c.shape)
print( a.shape)
c[0,4] = 1234
print(a)
print(id(a))
print(id(c))

False
(2, 6)
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
119858880
119859840


In [31]:
#The copy method makes a complete copy of the array and its data.
#复制 值和所指向的位置都不一样
d = a.copy() 
print(d is a)
d[0,0] = 9999
print (d)
print (a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
